language: android
android:
  components:
  - tools
  - android-23
  - build-tools-23.0.3
  - extra-google-google_play_services
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository


env:
  global:
    - secure: IPAA7M0TnFpO1NpG9E/qtt/PDa/gtmKoXYJcPbe7hevPKfQG6Vf34fL2L7UlOw1+bd50bjWPbK/t7DThThg9pdsoXbA2LjoDAyb/E5ycZdf0dOoqPMrcexqArCETHxpAtOWFfCZucNVaCVeue1cPcNW8qJrTtRYfFn2U3zuqVIR/wdge0CdY1Vm0y0Xi+OFjVZaS27HMXsAoU0NIzRBE1TRJTwcoYFl9KfgKt6qh3vJLyPaNQythlYN4ehvskvO0+pjX3j8fz+RjoR0TxcGnHvmPran2/BkAzFzy6cGVMo5pO75LR9VoZzX1uEV0KtjgdxUxeipqS4soyiZRNLGSK63mHqttv4P3cdvTDj6UqrIPyk5Iehcs74jReHXaea8erRUFU4SJx5EAq9ct8LfDe8xyG2RbYDXCcnOf+VuxAVIKZbgieq/a8X2UjoT2DtZ9+6lsGZyPzHetvYHosbSp9PMBuD9NFsJJ2fT6nSo31LAbujkbI+URV6JgNp8Ywr7DOxq0EV6KyJA2PkLD4QcbfNXi+pzVmw9C+3cKgU9z9tK9Hq8fWGN/ZWzi/oZjWdBmsXuPkfDOhbGqBpV0iTeH+o6s8X0IhTNclxmRUKbmy4C11EtG6gEudCblzC5fT1SKfgaTAVTyssTFjrKbZeDstu2fwtU2b2zV6ottf0QA5XU=
    - secure: XQxljAPYCh1mpsZUiAOmsbskteQNlq9RoFmG2+jKHNihQq/qHbvK3aymHS6ZccrePbs7cjMwBUWftASMAEoV5i9eH7KBhlefd0v8VqW0zC7/wLL3dAf2H8qShaqGwkovmOI6Rbd6OowUtAc3mfKYM+BIDf5IhO97kI8XtDG8FzRWN4DfGwvDPVCaNAu49h3BRX/SPwrMBjU/6YydTKttC8uXMSzgLI2K/e+qpeuctPf//q232yBoV207aD6a74eN9QP3YRRSB3IMFl49pS4dP+kFUbsMmrl266FFrphsBzTCYvXhU7GqhypJKm03Ger3lZIZtPZyMsHWyifQLKNBB0evAwoC0aa8mqyKYL3xkMXPs4PjFgh8D4BO4JU4VE8NmxgQDkPsD+dcuEniY9OqjIn/FXTMAzje1X+nAhu3kT5ue6rsrtt8YM9D9TBfJcZoNogf4bw0aiWXXF1tw5Qlo2yVHkeugHGuO8BXTIgXIonND9cFNB1u5FVVwh7+412BENf3LVbfuHUvvTVAxbpzHg9VwzJ9SCCWw04cfKFXH3YUtZvCwtp+MMaGVL/vcgQ3sBstzS7TJkqWdfWzoQW17OnPoFOF0X+1ZFr5M4QsCwrmMwLwiYmGplvSqkv/VIjvBgd3kYZaStGjZcaoW+R8wRlPVedlHDb+47U2fp/ZcPU=
    - secure: JncyNIy4QKZxOwPduq7qmORJtlvC6PpwuWztjO5Mx1vHv95xzkdGuhvxxZWcJnK4gKtSarrzH/6P9mA/OCxYwFx66WGR8DX4iBdnr8teO+/sK5akW3IA9gBK6RRY7qKyP3JjSIn8eRi6wy3ciCA5/1fVB0WXonTMEkaG3NVwxOw8/62U3Um+MrKO6oQq1P36zx5iIVN1Aq01JLxM8L+zLHCKoosA2MJex0alXs2u4CI9c/A2IdXVkvF8es2a7UkyfoY3PlQK5KkjfdoxDf7qUFCHdxnji10TUMNIFiUasBkzcYXtKeJbw8l3ZoR/d8GHfLKkvgt58R70JQZIbpxthqwiJfW3NsmZe16r1BWEC/mOguapeSR4AJIdf3qd/TKOf880TMJzN1hFKg9b86nGplKxovX9LAu7SZoycgEeRhZ18YgRo2ya3hE3ddbEVkqM/DLrlXzMpreU2Xz+uG7fWQVQSBS/ejoZmzCtBtPO37eeUVCKNb+N0s7rso1tBp0sLRA2Q/ThqjZCi14X4bPsdNDAejz6K9c+JtO+zwL+Fd+RaGWGY74N+2APLsKbKGSUENkN4kDWrNwGGHJiWF4VBSNs0y1q8IQVYKb/3F1+rOLRGyHzPH6bUIcsFbVf0U+3+mC8NZkw7e86iw3uMXC0i1UULFk/a3ncgOBO+7HE/1g=


before_install:
  - openssl aes-256-cbc -d -a -in keys.tar.enc -out keys.tar -k $DKey -iv $DIV
  - tar xvf keys.tar
  - mv ks.keystore app/

script: "./gradlew assemble --stacktrace --info"
after_success:
  - mv app/build/outputs/apk/app-release.apk wanthavers-$TRAVIS_BRANCH-`git rev-parse HEAD`.apk
  - curl -F "apk=@wanthavers-$TRAVIS_BRANCH-`git rev-parse HEAD`.apk" -F "project=wanthavers-android" $URL
